### ISSUE TITLE
Any time plan for this new RxJS docs?

### ISSUE THREAD

**Issue by SangKa** [ReactiveX/rxjs-docs#1]
Hi, @benlesh . Glad to know the plan for the new docs.
Does have any time plan for now? If has, please let me know :smile: , thx.

**Comment by ladyleet** [comment]
@SangKa we are working on it - if you'd like to contribute please email me tracy@thisdot.co // @benlesh

**Comment by inf3cti0n95** [comment]
@ladyleet I am also planning on contributing to creating awesome docs

**Comment by ladyleet** [comment]
@inf3cti0n95 okay please send me an email so i can add you to the meetings! :)

**Comment by inf3cti0n95** [comment]
@ladyleet Email Sent :)
