### ISSUE TITLE
Add docs for operator : transformation - bufferCount

### ISSUE THREAD

**Issue by ashwin-sureshkumar** [ReactiveX/rxjs-docs#110]
Add docs for operator bufferCount under group transformation 
 
Below is minimum details needed 
 
- [ ] name 
- [ ] operatorType 
- [ ] signature 
- [ ] parameters 
- [ ] short description 
- [ ] Technical description 
- [ ] Visual example  (Marble diagram) 
- [ ] Real world example (Non-framework) 
- [ ] Related Operators

**Comment by DiedrikDM** [comment]
I'll take this buffer method as well :)

**Comment by ladyleet** [comment]
thank you @DiedrikDM! helping us get the docs done! are you on our slack channel? email me so we can chat more! tracy@thisdot.co
