### ISSUE TITLE
Add docs for operator : transformation - bufferToggle

### ISSUE THREAD

**Issue by ashwin-sureshkumar** [ReactiveX/rxjs-docs#112]
Add docs for operator bufferToggle under group transformation 
 
Below is minimum details needed 
 
- [ ] name 
- [ ] operatorType 
- [ ] signature 
- [ ] parameters 
- [ ] short description 
- [ ] Technical description 
- [ ] Visual example  (Marble diagram) 
- [ ] Real world example (Non-framework) 
- [ ] Related Operators

**Comment by DiedrikDM** [comment]
Next one for me

**Comment by ladyleet** [comment]
You're awesome @diedrikDM!
