### ISSUE TITLE
Add docs for operator : transformation - map

### ISSUE THREAD

**Issue by ashwin-sureshkumar** [ReactiveX/rxjs-docs#117]
Add docs for operator map under group transformation 
 
Below is minimum details needed 
 
- [ ] name 
- [ ] operatorType 
- [ ] signature 
- [ ] parameters 
- [ ] short description 
- [ ] Technical description 
- [ ] Visual example  (Marble diagram) 
- [ ] Real world example (Non-framework) 
- [ ] Related Operators

**Comment by natmegs** [comment]
I have a PR ready for this as soon as JSbin is back up :)

**Comment by ladyleet** [comment]
@natmegs awesome! Might want to submit a WIP?

**Comment by natmegs** [comment]
Great, done. Would love any feedback with anything that needs to be changed!
