### ISSUE TITLE
Design a teams page

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs-docs#14]
[ ] Design page for approval
[ ] Core team
[ ] Learning team

**Comment by fredrik-lundin** [comment]
How big are the core and learning teams (approximately)? Does it make sense to somehow split the screen either in two sub-pages or tabs. Or is the number of people small enough to fit on one screen (which usual is preferable if possible I guess). 

Also, what kind of data do we want to present? Name, short bio, picture? Contact information?

**Comment by ladyleet** [comment]
@fredrik-lundin pretty small! I would say 5-10 people max for each category? One screen is preferred. Name, Short Bio (2 sentences max), Picture, Twitter, Github, LinkedIn?

**Comment by fredrik-lundin** [comment]
@ladyleet alright, great! 

I'm a bit unsure if I'll have to time work on it this week, as I'll be traveling for a few days. If someone starts looking at this before I can get too it, I'll just try to tag along when I get back. If not, I'll start working on it hopefully next week 😄

**Comment by ladyleet** [comment]
@fredrik-lundin for sure! i really appreciate you lending a hand! thank you so much in advance! :)

**Comment by fredrik-lundin** [comment]
@ladyleet hey, I finally got to start playing around a bit with this page. I noticed very quickly though that it's really hard since we don't have any design guidelines or basic  styling in place. That makes it very hard to style or design anything, since I feel like I might be completely misaligned with the rest of the people working on this.

It would be very useful to have some kind of core design in place. Basic things like:
* How wide is the main content area
* How are we doing in terms of responsive design (some set breakpoints?)
* Common styling for basic elements like header, sections, field sets, etc

Maybe those points belongs to a separate issue though :)

**Comment by fredrik-lundin** [comment]
Here is a first, very simply, idea. Just cards with a small avatar (can for example use the one from github, _github.com/user-name.png_). Name, role, bio, links. Then just different background colors for _Core_ and _Learning_ team 

![team-first-wip](https://user-images.githubusercontent.com/5526934/31650834-771fc3d6-b319-11e7-88a8-fb6ceab3de36.gif)

**Comment by ladyleet** [comment]
Hi @fredrik-lundin! thank you so much! That is basically exactly what we are looking for. I would emphasize the images and perhaps iterate on something like this? 

<img width="756" alt="screenshot 2017-10-19 09 58 51" src="https://user-images.githubusercontent.com/8270563/31783741-35d0e9ea-b4b4-11e7-8bed-afec627be01f.png">

**Comment by xlozinguez** [comment]
Can the team be extracted from the list of github contributors in order to avoid manual maintenance as much as can be?

**Comment by ladyleet** [comment]
@xlozinguez nope - it's a pretty small list and doesn't change often so it should not be that high maintenance.

**Comment by fredrik-lundin** [comment]
@ladyleet - working on something like this. Some tweaks to the text styling probably needed, but this should be more aligned with what you are thinking, right?

![image](https://user-images.githubusercontent.com/5526934/31821446-6c14692c-b5a5-11e7-91d4-5a77531be40b.png)

**Comment by ladyleet** [comment]
@fredrik-lundin awesome! looking forward to seeing that PR!

**Comment by Only1MrAnderson** [comment]
@fredrik-lundin Are you able to submit your work for this? If not I will pick it up.

**Comment by fredrik-lundin** [comment]
@Only1MrAnderson Hi! I'm so sorry that I haven't had time to work on this at all in so long. Completely side tracked by.. life.. I will look into finishing up a PR this weekend. Or would you rather start from scratch?

**Comment by ladyleet** [comment]
@fredrik-lundin have any time to finish this up? let me know what support you need from me!

**Comment by sumitarora** [comment]
@fredrik-lundin Can you push the PR whatever you have done?

**Comment by fredrik-lundin** [comment]
Aaaargh, sorrryy!! I'll push what I have tonight!

**Comment by ladyleet** [comment]
thanks @fredrik-lundin

**Comment by fredrik-lundin** [comment]
@ladyleet submitted a PR!

**Comment by ladyleet** [comment]
thanks @fredrik-lundin

**Comment by ladyleet** [comment]
thanks!
