### ISSUE TITLE
How to deal with potentially unsafe HTML inside OperatorDocs?

### ISSUE THREAD

**Issue by nicolaisueper** [ReactiveX/rxjs-docs#151]
Hey there,

while working on #149, I was requested to put a link to another operator inside the OperatorDoc for combineLatest. My `href` attribute got sanitized and it resulted in `<a>.startWith</a>`.

I temporarily created a `SafeHtmlPipe` (analogous to the `SafeUrlPipe`), which bypasses the sanitizing. 

I wanted to know if you all agree with my solution or maybe anyone else has an idea how to deal with issues like this.

Greets
Nico

**Comment by btroncone** [comment]
Hmm, this shouldn't be the case. We are binding to`[innerHTML]` elsewhere without issue. I attempted to recreate this locally and did not receive an error. I will need to look more closely at your branch to see if there is something I missed.

**Comment by nicolaisueper** [comment]
Try to check out my branch and remove the safeHtml pipe from the operator-extras.component.html

**Comment by nicolaisueper** [comment]
Now I'm confused. I removed it myself and it didn't complain. Closing this. 🤔
