### ISSUE TITLE
Prefer const in code examples

### ISSUE THREAD

**Issue by btroncone** [ReactiveX/rxjs-docs#178]
We currently have a mix of `var`, `let`, and `const` in the operator examples. I think we should standardize on one or the other to be consistent, my preference would be `const`. Thoughts?

**Comment by ashwin-sureshkumar** [comment]
I agree

**Comment by ladyleet** [comment]
👍

**Comment by mustafamg** [comment]
Me too.

**Comment by JWO719** [comment]
isn't this one closed with #179 ?

**Comment by ashwin-sureshkumar** [comment]
@JWO719 - Yes. Closing. Thank you.
