### ISSUE TITLE
Have a better readme.md

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs-docs#19]
Well, ours kind of sucks rn. Open to suggestions.

**Comment by bhatiatanish** [comment]
I'd like to take up this issue. Can you assign it to me?

**Comment by ladyleet** [comment]
hi @bhatiatanish we are not currently assigning folks to issues, but are accepting PRs! If anyone else is looking at this issue and would like to contribute, please coordinate with @bhatiatanish so y'all don't cross wires! :) 💯

**Comment by lordKnighton** [comment]
I'll pitch in with this, when ever i get some time. Sounds fun 💯

**Comment by ladyleet** [comment]
Thx @knittingcodemonkey for this! Closing out this issue.
