### ISSUE TITLE
Documentation guidelines

### ISSUE THREAD

**Issue by DiedrikDM** [ReactiveX/rxjs-docs#247]
Hi everybody,

It's currently not easy to find any guidelines about how our documentation should look like. There are currently a couple of things that I learned while adding four PRs to the documentation and I would like to summarize those into a DOCUMENTATION_GUIDELINES.md file. I will start by adding a new PR to add that file and afterwards we can still modify it when necessary.

**Comment by JWO719** [comment]
Sounds really good for me. Great idea :+1:

**Comment by JWO719** [comment]
The pr is already merged, so this issue can be closed

**Comment by DiedrikDM** [comment]
@JWO719 thanks for the reminder 👍
