### ISSUE TITLE
Connecting this an rxjs/master efforts

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs-docs#249]
We need to make sure that the rxjs/master README guides people to this stuff.

Please see this here: https://github.com/ReactiveX/rxjs/issues/3272

**Comment by JWO719** [comment]
If I understand you correctly maybe this pr #248 is a good start. Perhaps we could just link to file if its merged?!

**Comment by ladyleet** [comment]
@benlesh thoughts?

**Comment by ladyleet** [comment]
@JWO719 i like this - do you want to go ahead and submit a PR to rxjs and tag myself and ben on this?

**Comment by JWO719** [comment]
Yeah ofc. :smiley:

**Comment by JWO719** [comment]
Pr is merged in rxjs repo. So this one can closed.

**Comment by benlesh** [comment]
Thanks @JWO719
