### ISSUE TITLE
Bug: On mobile sizes, close the menu automatically once an operator is selected.

### ISSUE THREAD

**Issue by knittingcodemonkey** [ReactiveX/rxjs-docs#277]
At the moment, when you select an operator, the side menu doesn't close. You can close it by pressing escape, but the menu should close by default. We do want to continue to show the side menu at larger sizes that can support the width.

**Comment by jsonberry** [comment]
I wonder if there's something we could do like a "skip to main" when a user clicks on an operator sidenav item, instead of just closing the menu. 

Our main concern for a11y is to get the user to the main content after making the selection, right?
