### ISSUE TITLE
Learning team meeting notes

### ISSUE THREAD

**Issue by ladyleet** [ReactiveX/rxjs-docs#32]
https://github.com/emberjs/core-notes - chatting with @mattpodwysocki and @benlesh about a repo for all core notes in the reactivex project, not just the docs. also, this would be good for the rxjs core notes.

**Comment by kwonoj** [comment]
I think we can just use https://github.com/ReactiveX/rxjs-core-notes? Creating new folder for docs.

**Comment by ladyleet** [comment]
@kwonoj thanks! @mattpodwysocki disregard my request then. :)
