### ISSUE TITLE
Basic tooling

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs-docs#45]
anyone up for setting up lint / prettier, etcs for consistent codes? except prettier it's available in RxJS repo already so copy-paste would be sufficient.

**Comment by ashwin-sureshkumar** [comment]
@kwonoj I can pick this

**Comment by kwonoj** [comment]
go for it 👍

**Comment by kwonoj** [comment]
one thing: prolly we need setup prettier for `lint-staged` stage as same as lint for faster processing.

**Comment by ladyleet** [comment]
Thx @ashwin-sureshkumar

**Comment by kwonoj** [comment]
+ with `husky` git hooks, I meant.

**Comment by ashwin-sureshkumar** [comment]
@kwonoj - just clarify you are looking to add the husky hooks on pre-commit or pre-push. Also, run the test + lint on decided husky hook or just lint ? I was thinking both test + lint.

**Comment by kwonoj** [comment]
what rxjs repo does is precommit for lint-staged only. reason it is precommit is it has autofix, so each commit has correct one right away. I'd probably not consider prepush at this moment especially test - let it run by CI.

**Comment by ashwin-sureshkumar** [comment]
@kwonoj - Thanks !
