### ISSUE TITLE
Accessibility - Figure out how to skip, or exit JSBin in content

### ISSUE THREAD

**Issue by knittingcodemonkey** [ReactiveX/rxjs-docs#62]
I couldn't figure out how to navigate beyond the first JSBin to continue onto the rest of the page. Is there a keyboard shortcut for skipping it, or getting out of it once you've tabbed into the JSBin?
https://webaim.org/techniques/skipnav/

**Comment by btroncone** [comment]
Thanks for looking into this, we could certainly add a keyboard shortcut if that would help. What would your suggestion be? I'm also not sure JSBin will be what we use when all is said and done but I would imagine it's likely we hit the same issue with any embed?

**Comment by knittingcodemonkey** [comment]
I'm looking into some standards for skipping the examples and exiting them. It just sucked to try navigating through the page, and get stuck in an example with no way out using only a keyboard.

**Comment by btroncone** [comment]
Awesome, thanks for all of your help!

**Comment by ladyleet** [comment]
@knittingcodemonkey you're kind of the best Jen!

**Comment by knittingcodemonkey** [comment]
It sounds like <ESC> is the key of choice for getting out of playground code examples.

**Comment by knittingcodemonkey** [comment]
It appears that ALT-TAB or OPTION-TAB works to escape the JSBin. This solves my concern with this issue.
