### ISSUE TITLE
Add docs for operator : combinational - concat 

### ISSUE THREAD

**Issue by ashwin-sureshkumar** [ReactiveX/rxjs-docs#63]
Add docs for operator `concat` under group `combinational`

Below is minimum details needed 

- [ ] name
- [ ] operatorType
- [ ] signature
- [ ] parameters
- [ ] short description
- [ ] Technical description
- [ ] Visual example  (Marble diagram)
- [ ] Real world example (Non-framework)
- [ ] Related Operators

**Comment by btroncone** [comment]
Looks pretty good. Currently on docs all operators also feature a longer, more technical explanation. I think that should also be ported over along with the related operators block. Thanks for doing this! 👍

**Comment by ladyleet** [comment]
:+1:
