### ISSUE TITLE
Add docs for operator : filtering - last

### ISSUE THREAD

**Issue by ashwin-sureshkumar** [ReactiveX/rxjs-docs#94]
Add docs for operator last under group filtering 
 
Below is minimum details needed 
 
- [ ] name 
- [ ] operatorType 
- [ ] signature 
- [ ] parameters 
- [ ] short description 
- [ ] Technical description 
- [ ] Visual example  (Marble diagram) 
- [ ] Real world example (Non-framework) 
- [ ] Related Operators

**Comment by JWO719** [comment]
I would give this a try, if no one is already working on it.
